### ISSUE TITLE
Missing version tags

### ISSUE THREAD

**Issue by wulmer** [cokelaer/spectrum#8]
Hi,

on PyPI, there are different versions of this package but I can't find the corresponding commits here on GitHub. Could you please add version labels/tags to your commits which lead/led to versions on PyPI ?

The reason is that I would like to build conda packages for your package which is much more comfortable to use with Git tags than with PyPI archive files.

Thanks!

Wolfgang

**Comment by cokelaer** [comment]
Hi Wolfgang,
I've just upload a new version on spectrum on pypi (version 0.6.1) and I have added a tag within git (called v0.6.1). 
I hope this will help
Best
Thomas

**Comment by wulmer** [comment]
Great, thanks! It works fine!

I am using the following conda recipe to [build a conda package](http://conda.pydata.org/docs/building/recipe.html) for spectrum:
```
package:
  name: spectrum
  version: "0.6.1"

source:
  git_url: https://github.com/cokelaer/spectrum.git
  git_tag: "v0.6.1"

  patches:
    - remove_easydev.patch

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - numpy
    - scipy

  run:
    - python
    - matplotlib
    - numpy
    - scipy

test:
  imports:
    - cpp
    - spectrum

about:
  home: http://www.assembla.com/spaces/PySpectrum/wiki
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'Spectrum Analysis Tools'
```
The patch file `remove_easydev.patch` mentioned in the recipe just removes the `easydev` dependency from the `setup.py` file as the docs are not build for the conda package and therefore `easydev` is not needed for building the conda package.
